### ISSUE TITLE
NVME Support

### ISSUE THREAD

**Issue by khaytsus** [glenpp/cacti-smart#1]
First off, thank you, this was a great fast SMART template for Cacti, it took about 10m for two machines to get up and running, and that was being a few years since I've really dug into Cacti besides looking at output from it.

I tried to add NVME to the script, but from what I can tell the output from smartctl is different so it's not going to parse it.  Is this something that you could do or would be interesting in doing?   I'll attach a smartctl -a output from one of my nvme drives if it's useful.  I suspect it's just a smart-generic script update to handle it.  The format, oddly, is quite different.

[dev_nvme0n1.txt](https://github.com/glenpp/cacti-smart/files/1036101/dev_nvme0n1.txt)

**Comment by glenpp** [comment]
Sorry for the long time getting round to answering this.

When we move to more specialist devices then the data does look completely different and it's unlikely to be practical to support these with this tool without making things much more complicated. Along with that the way we architect systems has changed enormously since I originally created this so drive monitoring is much less of an itch to scratch now and in Enterprise/Specialist contexts is often taken care of with vendor service agreements and vendor supplied tools anyway. For me these templates are left only used on my home setup (workstations, lab storage server etc.)

You are welcome to fork the project and adapt it for your needs and maybe some others that have the need to monitor similar devices will also get value from that.

**Comment by khaytsus** [comment]
NVME isn't specialty stuff anymore; I built a desktop for someone for $350 with an NVME drive.  I have several in my desktop.  I understand the response regardless, but wanted to point out that NVME isn't an enterprise solution and I'm not even sure that it started as one.

And yes, this is primarily for me to monitor my personal machines as well.  None the less I do get some useful data, so I appreciate the work.  :)
